# Generated by Django 6.0.7 on 2026-08-02 12:38

import apps.purchasing.models
import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0013_remove_financebudgetline_unique_finance_budget_line_per_month_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(default=apps.purchasing.models.generate_purchase_request_number, editable=False, max_length=30, unique=True, verbose_name='Talep numarası')),
                ('title', models.CharField(max_length=180, verbose_name='Talep başlığı')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending_approval', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('needed_by_date', models.DateField(blank=True, null=True, verbose_name='İhtiyaç tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Talep açıklaması')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Onaya gönderim zamanı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='Ret gerekçesi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='organizations.company', verbose_name='Şirket')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep eden kullanıcı')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Onaya gönderen kullanıcı')),
            ],
            options={
                'verbose_name': 'Satın alma talebi',
                'verbose_name_plural': 'Satın alma talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Kalem açıklaması')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Birim fiyat')),
                ('needed_by_date', models.DateField(default=datetime.date.today, verbose_name='İhtiyaç tarihi')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('budget_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='finance.financebudgetaccount', verbose_name='Bütçe kontrol hesabı')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaserequest', verbose_name='Satın alma talebi')),
            ],
            options={
                'verbose_name': 'Satın alma talep kalemi',
                'verbose_name_plural': 'Satın alma talep kalemleri',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['company', 'status', 'created_at'], name='purchasing__company_0209ae_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['purchase_request', 'budget_account'], name='purchasing__purchas_668710_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_request_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_request_line_unit_price_nonnegative'),
        ),
    ]
