# Generated by Django 6.0.7 on 2026-08-02 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_financebudgetline_unique_finance_budget_line_per_month_and_more'),
        ('organizations', '0003_company_tax_office'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBudgetCommitment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.DateField(verbose_name='Bütçe ayı')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Taahhüt tutarı')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('released', 'Serbest bırakıldı'), ('cancelled', 'İptal edildi')], default='active', max_length=12, verbose_name='Durum')),
                ('budget_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_budget_commitments', to='finance.financebudgetaccount', verbose_name='Bütçe kontrol hesabı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_budget_commitments', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_budget_commitments', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_commitments', to='purchasing.purchaserequest', verbose_name='Satın alma talebi')),
                ('purchase_request_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget_commitment', to='purchasing.purchaserequestline', verbose_name='Satın alma talep kalemi')),
            ],
            options={
                'verbose_name': 'Satın alma bütçe taahhüdü',
                'verbose_name_plural': 'Satın alma bütçe taahhütleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'budget_account', 'period_month', 'status'], name='purchasing__company_41e2b4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchase_budget_commitment_amount_positive')],
            },
        ),
    ]
