# Generated by Django 6.0.7 on 2026-08-02 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_company_tax_office'),
        ('purchasing', '0002_purchasebudgetcommitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, verbose_name='Tedarikçi kodu')),
                ('name', models.CharField(max_length=180, verbose_name='Tedarikçi adı')),
                ('legal_name', models.CharField(blank=True, max_length=220, verbose_name='Resmî unvan')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi numarası')),
                ('tax_office', models.CharField(blank=True, max_length=120, verbose_name='Vergi dairesi')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='Yetkili kişi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('payment_term_days', models.PositiveSmallIntegerField(default=30, verbose_name='Standart ödeme vadesi (gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='purchasing__company_f2e22c_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='unique_supplier_code_per_company')],
            },
        ),
    ]
