# Generated by Django 6.0.7 on 2026-08-02 16:44

import apps.purchasing.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_financebudgetline_unique_finance_budget_line_per_month_and_more'),
        ('organizations', '0003_company_tax_office'),
        ('purchasing', '0003_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(default=apps.purchasing.models.generate_purchase_order_number, editable=False, max_length=30, unique=True, verbose_name='Sipariş numarası')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Tedarikçiye gönderildi'), ('confirmed', 'Tedarikçi onayladı'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sipariş tarihi')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Beklenen teslim tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Sipariş notu')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim zamanı')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='organizations.company', verbose_name='Şirket')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan kullanıcı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='purchasing.purchaserequest', verbose_name='Kaynak satın alma talebi')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Tedarikçiye gönderen kullanıcı')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Satın alma siparişi',
                'verbose_name_plural': 'Satın alma siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Kalem açıklaması')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sipariş miktarı')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Birim fiyat')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Teslim alınan miktar')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Beklenen teslim tarihi')),
                ('budget_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='finance.financebudgetaccount', verbose_name='Bütçe kontrol hesabı')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='Satın alma siparişi')),
                ('purchase_request_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_line', to='purchasing.purchaserequestline', verbose_name='Kaynak talep kalemi')),
            ],
            options={
                'verbose_name': 'Satın alma sipariş kalemi',
                'verbose_name_plural': 'Satın alma sipariş kalemleri',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', 'status', 'created_at'], name='purchasing__company_662f70_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchasing__supplie_dddc8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_order_line_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='purchase_order_line_received_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='purchase_order_line_received_quantity_within_order'),
        ),
    ]
