# Generated by Django 6.0.7 on 2026-08-02 17:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_company_tax_office'),
        ('purchasing', '0004_purchaseorder_purchaseorderline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Tedarikçiye gönderildi'), ('confirmed', 'Tedarikçi onayladı'), ('partially_received', 'Kısmi teslim alındı'), ('received', 'Tam teslim alındı'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Teslim alma tarihi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Teslim alınan miktar')),
                ('reference_number', models.CharField(blank=True, max_length=80, verbose_name='İrsaliye / teslim referansı')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Teslim alma notu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_receipts', to='organizations.company', verbose_name='Şirket')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorderline', verbose_name='Sipariş kalemi')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchase_order_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Teslim alan kullanıcı')),
            ],
            options={
                'verbose_name': 'Sipariş teslim kaydı',
                'verbose_name_plural': 'Sipariş teslim kayıtları',
                'ordering': ['-receipt_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'receipt_date'], name='purchasing__company_73da34_idx'), models.Index(fields=['purchase_order_line', 'receipt_date'], name='purchasing__purchas_c550fe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_order_receipt_quantity_positive')],
            },
        ),
    ]
