# Generated by Django 6.0.7 on 2026-08-02 18:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_company_tax_office'),
        ('purchasing', '0005_alter_purchaseorder_status_purchaseorderreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=80, verbose_name='Tedarikçi fatura numarası')),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fatura tarihi')),
                ('due_date', models.DateField(verbose_name='Vade tarihi')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending_approval', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('partially_paid', 'Kısmi ödendi'), ('paid', 'Ödendi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Fatura notu')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchasing.purchaseorder', verbose_name='Satın alma siparişi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Tedarikçi faturası',
                'verbose_name_plural': 'Tedarikçi faturaları',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Fatura kalemi açıklaması')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Faturalanan miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Birim fiyat')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='purchasing.purchaseorderline', verbose_name='Sipariş kalemi')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.supplierinvoice', verbose_name='Tedarikçi faturası')),
            ],
            options={
                'verbose_name': 'Tedarikçi fatura kalemi',
                'verbose_name_plural': 'Tedarikçi fatura kalemleri',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['company', 'status', 'due_date'], name='purchasing__company_8eec98_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier', 'status'], name='purchasing__supplie_7de837_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'supplier', 'invoice_number'), name='unique_supplier_invoice_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='supplier_invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='supplier_invoice_line_unit_price_nonnegative'),
        ),
    ]
