# Generated by Django 6.0.7 on 2026-08-03 06:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_financebudgetline_unique_finance_budget_line_per_month_and_more'),
        ('organizations', '0003_company_tax_office'),
        ('purchasing', '0006_supplierinvoice_supplierinvoiceline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoicePayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Ödeme tutarı')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ödeme tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('reversed', 'Ters kayıt'), ('cancelled', 'İptal')], default='active', max_length=12, verbose_name='Durum')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_payments', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoice_payments', to=settings.AUTH_USER_MODEL, verbose_name='Ödemeyi kaydeden kullanıcı')),
                ('financial_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_payment', to='finance.financialaccounttransaction', verbose_name='Kasa / banka ödeme hareketi')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchasing.supplierinvoice', verbose_name='Tedarikçi faturası')),
            ],
            options={
                'verbose_name': 'Tedarikçi faturası ödemesi',
                'verbose_name_plural': 'Tedarikçi faturası ödemeleri',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'supplier_invoice', 'status'], name='purchasing__company_417553_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_invoice_payment_amount_positive')],
            },
        ),
    ]
