# Generated by Django 6.0.7 on 2026-07-26 19:25

import apps.sales.models
import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_opportunity_labels_opportunity_last_contacted_at_and_more'),
        ('organizations', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(default=apps.sales.models.generate_order_number, editable=False, max_length=30, unique=True, verbose_name='Sipariş numarası')),
                ('status', models.CharField(choices=[('confirmed', 'Onaylandı'), ('in_production', 'Üretimde'), ('ready_to_ship', 'Sevkiyata Hazır'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='confirmed', max_length=20, verbose_name='Durum')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Sipariş tarihi')),
                ('planned_delivery_date', models.DateField(blank=True, null=True, verbose_name='Planlanan teslim tarihi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ara toplam')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='KDV tutarı')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Genel toplam')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='organizations.company', verbose_name='Şirket')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='crm.customer', verbose_name='Müşteri')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu kullanıcı')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='sales.salesquote', verbose_name='Kaynak teklif')),
            ],
            options={
                'verbose_name': 'Satış siparişi',
                'verbose_name_plural': 'Satış siparişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Ürün veya hizmet')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Birim fiyat')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='KDV oranı')),
                ('line_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Satış sipariş kalemi',
                'verbose_name_plural': 'Satış sipariş kalemleri',
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'status'], name='sales_sales_company_6440e1_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'customer'], name='sales_sales_company_43dd8a_idx'),
        ),
    ]
