# Generated by Django 6.0.7 on 2026-07-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_salesorder_salesorderline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesquoteline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quote_lines', to='inventory.product', verbose_name='Ürün kartı'),
        ),
    ]
