# Generated by Django 6.0.7 on 2026-07-28 17:30

import apps.sales.models
import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_billing_address_customer_tax_office'),
        ('inventory', '0003_alter_warehouse_branch'),
        ('organizations', '0003_company_tax_office'),
        ('sales', '0004_salesorderline_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(default=apps.sales.models.generate_invoice_number, editable=False, max_length=30, unique=True, verbose_name='Fatura numarası')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('issued', 'Kesildi'), ('sent', 'E-posta ile gönderildi'), ('partially_paid', 'Kısmi ödendi'), ('paid', 'Ödendi'), ('overdue', 'Vadesi geçti'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='Fatura tarihi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade tarihi')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Kesilme zamanı')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme zamanı')),
                ('seller_name', models.CharField(max_length=200, verbose_name='Satıcı adı')),
                ('seller_legal_name', models.CharField(blank=True, max_length=220, verbose_name='Satıcı resmî unvanı')),
                ('seller_tax_number', models.CharField(blank=True, max_length=30, verbose_name='Satıcı vergi numarası')),
                ('seller_tax_office', models.CharField(blank=True, max_length=120, verbose_name='Satıcı vergi dairesi')),
                ('seller_email', models.EmailField(blank=True, max_length=254, verbose_name='Satıcı e-posta adresi')),
                ('seller_phone', models.CharField(blank=True, max_length=30, verbose_name='Satıcı telefon numarası')),
                ('seller_address', models.TextField(blank=True, verbose_name='Satıcı adresi')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Müşteri adı')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Müşteri e-posta adresi')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='Müşteri telefon numarası')),
                ('customer_tax_number', models.CharField(blank=True, max_length=30, verbose_name='Müşteri vergi numarası')),
                ('customer_tax_office', models.CharField(blank=True, max_length=120, verbose_name='Müşteri vergi dairesi')),
                ('customer_address', models.TextField(blank=True, verbose_name='Müşteri fatura adresi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ara toplam')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='KDV tutarı')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Genel toplam')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Doğrulama kodu')),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/%Y/%m/', verbose_name='PDF dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.customer', verbose_name='Müşteri')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.salesorder', verbose_name='Kaynak satış siparişi')),
            ],
            options={
                'verbose_name': 'Satış faturası',
                'verbose_name_plural': 'Satış faturaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Ürün veya hizmet')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Birim fiyat')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='KDV oranı')),
                ('line_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice', verbose_name='Fatura')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.product', verbose_name='Ürün kartı')),
            ],
            options={
                'verbose_name': 'Fatura kalemi',
                'verbose_name_plural': 'Fatura kalemleri',
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status'], name='sales_invoi_company_539c70_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'issue_date'], name='sales_invoi_company_b1c137_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='sales_invoi_custome_68fcf9_idx'),
        ),
    ]
