# Generated by Django 6.0.7 on 2026-07-29 11:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_invoice_invoiceline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='İskonto tutarı'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='KDV matrahı'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='İskonto oranı'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='İskonto tutarı'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='KDV matrahı'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='İskonto oranı'),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='İskonto tutarı'),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='KDV matrahı'),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='İskonto oranı'),
        ),
    ]
