# Generated by Django 6.0.7 on 2026-07-24 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Pozisyon')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Birincil üyelik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.branch', verbose_name='Şube')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.company', verbose_name='Şirket')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='organizations.department', verbose_name='Departman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Organizasyon üyeliği',
                'verbose_name_plural': 'Organizasyon üyelikleri',
                'ordering': ('company', 'branch', 'department', 'user'),
                'constraints': [models.UniqueConstraint(fields=('user', 'company', 'branch', 'department'), name='unique_user_organization_membership')],
            },
        ),
    ]
