# Generated by Django 6.0.7 on 2026-07-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Sahip'), ('admin', 'Yönetici'), ('manager', 'Müdür'), ('member', 'Üye'), ('viewer', 'Görüntüleyici')], default='member', max_length=20, verbose_name='Çalışma alanı rolü'),
        ),
    ]
