# Generated by Django 6.0.7 on 2026-07-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizationmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'Sistem'), ('dark', 'Koyu'), ('light', 'Açık')], default='system', max_length=10, verbose_name='Tema tercihi'),
        ),
    ]
