# Generated by Django 6.0.7 on 2026-07-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Role ek olarak tanımlanan özel çalışma alanı izinleri.', verbose_name='Ek izinler'),
        ),
    ]
