# Generated by Django 6.0.7 on 2026-08-05 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=30, verbose_name='AI sağlayıcısı')),
                ('default_model', models.CharField(default='gpt-5.6-sol', max_length=120, verbose_name='Varsayılan model')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=120, verbose_name='Embedding modeli')),
                ('request_timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='İstek zaman aşımı')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='AI aktif mi?')),
                ('structured_output_enabled', models.BooleanField(default=True, verbose_name='Yapılandırılmış çıktı aktif mi?')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configuration', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'AI sağlayıcı ayarı',
                'verbose_name_plural': 'AI sağlayıcı ayarları',
                'ordering': ('company__name',),
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='openai', max_length=30, verbose_name='AI sağlayıcısı')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('module', models.CharField(max_length=50, verbose_name='ERP modülü')),
                ('feature', models.CharField(max_length=100, verbose_name='AI özelliği')),
                ('request_type', models.CharField(choices=[('text', 'Metin üretimi'), ('structured', 'Yapılandırılmış çıktı'), ('embedding', 'Embedding'), ('tool_call', 'Araç çağrısı'), ('rag', 'RAG sorgusu')], default='text', max_length=20, verbose_name='İstek türü')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Girdi token sayısı')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='Çıktı token sayısı')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Toplam token sayısı')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='Yanıt süresi (ms)')),
                ('request_metadata', models.JSONField(blank=True, default=dict, verbose_name='İstek metadatası')),
                ('response_metadata', models.JSONField(blank=True, default=dict, verbose_name='Yanıt metadatası')),
                ('error_type', models.CharField(blank=True, max_length=160, verbose_name='Hata türü')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata özeti')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to='organizations.company', verbose_name='Şirket')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL, verbose_name='İsteği yapan kullanıcı')),
            ],
            options={
                'verbose_name': 'AI istek kaydı',
                'verbose_name_plural': 'AI istek kayıtları',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'module', 'status'], name='ai_core_air_company_57e246_idx'), models.Index(fields=['company', 'request_type', 'created_at'], name='ai_core_air_company_e4f4f9_idx')],
            },
        ),
    ]
