# Generated by Django 6.0.8 on 2026-08-05 13:16

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_enable_vector_extension'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('candidate_resume', 'Aday öz geçmişi'), ('job_requisition', 'İşe alım talebi'), ('hr_policy', 'İK politikası'), ('finance_policy', 'Finans politikası'), ('product_document', 'Ürün dokümanı'), ('customer_document', 'Müşteri dokümanı'), ('supplier_document', 'Tedarikçi dokümanı'), ('erp_help', 'ERP yardım dokümanı'), ('other', 'Diğer')], max_length=40, verbose_name='Doküman türü')),
                ('source_type', models.CharField(choices=[('file_upload', 'Dosya yükleme'), ('erp_record', 'ERP kaydı'), ('manual', 'Manuel içerik'), ('generated', 'Sistem tarafından üretildi')], default='manual', max_length=30, verbose_name='Kaynak türü')),
                ('title', models.CharField(max_length=240, verbose_name='Başlık')),
                ('source_reference', models.CharField(blank=True, max_length=500, verbose_name='Kaynak referansı')),
                ('content_text', models.TextField(blank=True, verbose_name='Ham metin içeriği')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='İçerik özeti')),
                ('status', models.CharField(choices=[('pending', 'İndeksleme bekliyor'), ('processing', 'İşleniyor'), ('indexed', 'İndekslendi'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='İndeksleme durumu')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Doküman metadatası')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='İndekslenme zamanı')),
                ('error_message', models.TextField(blank=True, verbose_name='İşleme hata özeti')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_knowledge_documents', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
            ],
            options={
                'verbose_name': 'AI bilgi dokümanı',
                'verbose_name_plural': 'AI bilgi dokümanları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(verbose_name='Parça sırası')),
                ('content', models.TextField(verbose_name='Parça içeriği')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Parça içerik özeti')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Tahmini token sayısı')),
                ('embedding_model', models.CharField(blank=True, max_length=120, verbose_name='Embedding modeli')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True, verbose_name='Embedding vektörü')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Parça metadatası')),
                ('embedded_at', models.DateTimeField(blank=True, null=True, verbose_name='Embedding üretim zamanı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_knowledge_chunks', to='organizations.company', verbose_name='Şirket')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_core.aiknowledgedocument', verbose_name='Bilgi dokümanı')),
            ],
            options={
                'verbose_name': 'AI bilgi parçası',
                'verbose_name_plural': 'AI bilgi parçaları',
                'ordering': ('document', 'chunk_index'),
            },
        ),
        migrations.AddIndex(
            model_name='aiknowledgedocument',
            index=models.Index(fields=['company', 'document_type', 'status'], name='ai_core_aik_company_d5f481_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgedocument',
            index=models.Index(fields=['company', 'source_type', 'created_at'], name='ai_core_aik_company_bf742f_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['company', 'document', 'chunk_index'], name='ai_core_aik_company_934895_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['company', 'embedding_model'], name='ai_core_aik_company_b93acf_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiknowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_ai_chunk_index_per_document'),
        ),
    ]
