# Generated by Django 6.0.8 on 2026-08-06 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0003_aiknowledgedocument_aiknowledgechunk_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Yeni sohbet', max_length=180, verbose_name='Sohbet başlığı')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('archived', 'Arşivlendi')], db_index=True, default='active', max_length=20, verbose_name='Durum')),
                ('last_response_id', models.CharField(blank=True, max_length=255, verbose_name='Son OpenAI yanıt kimliği')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Son mesaj zamanı')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Sohbet metadatası')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Sohbet sahibi')),
            ],
            options={
                'verbose_name': 'AI sohbeti',
                'verbose_name_plural': 'AI sohbetleri',
                'ordering': ('-last_message_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Kullanıcı'), ('assistant', 'Asistan'), ('system', 'Sistem')], db_index=True, max_length=20, verbose_name='Mesaj rolü')),
                ('content', models.TextField(verbose_name='Mesaj içeriği')),
                ('model_name', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('response_id', models.CharField(blank=True, max_length=255, verbose_name='OpenAI yanıt kimliği')),
                ('round_count', models.PositiveIntegerField(default=0, verbose_name='AI turu')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='Araç çağrıları')),
                ('knowledge_sources', models.JSONField(blank=True, default=list, verbose_name='Bilgi kaynakları')),
                ('token_usage', models.JSONField(blank=True, default=dict, verbose_name='Token kullanımı')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='Yanıt süresi')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Mesaj metadatası')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_messages', to='organizations.company', verbose_name='Şirket')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_core.aiconversation', verbose_name='Sohbet')),
            ],
            options={
                'verbose_name': 'AI sohbet mesajı',
                'verbose_name_plural': 'AI sohbet mesajları',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['company', 'created_by', 'status', 'last_message_at'], name='ai_conv_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_message_conversation_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['company', 'role', 'created_at'], name='ai_message_company_role_idx'),
        ),
    ]
