# Generated by Django 6.0.8 on 2026-08-06 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0004_aiconversation_aiconversationmessage_and_more'),
        ('organizations', '0003_company_tax_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('image', 'Görsel')], db_index=True, default='image', max_length=20, verbose_name='Ek türü')),
                ('file', models.FileField(upload_to='ai/conversations/%Y/%m/%d/', verbose_name='Dosya')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Orijinal dosya adı')),
                ('content_type', models.CharField(max_length=120, verbose_name='İçerik türü')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Dosya boyutu')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Ek metadatası')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_attachments', to='organizations.company', verbose_name='Şirket')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai_core.aiconversationmessage', verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'AI sohbet eki',
                'verbose_name_plural': 'AI sohbet ekleri',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['company', 'attachment_type', 'created_at'], name='ai_attachment_company_type_idx')],
            },
        ),
    ]
