# Generated by Django 6.0.8 on 2026-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0005_aiconversationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfiguration',
            name='rag_enabled',
            field=models.BooleanField(default=True, verbose_name='RAG aktif mi?'),
        ),
        migrations.AddField(
            model_name='aiproviderconfiguration',
            name='rag_minimum_similarity',
            field=models.FloatField(default=0.35, verbose_name='Minimum RAG benzerliği'),
        ),
        migrations.AddField(
            model_name='aiproviderconfiguration',
            name='rag_top_k',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='RAG sonuç limiti'),
        ),
    ]
