# Generated by Django 6.0.7 on 2026-07-29 17:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0005_customer_billing_address_customer_tax_office'),
        ('organizations', '0003_company_tax_office'),
        ('sales', '0006_invoice_discount_amount_invoice_taxable_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_accounts', to='organizations.company', verbose_name='Şirket')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='crm.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Cari hesap',
                'verbose_name_plural': 'Cari hesaplar',
                'ordering': ['customer__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('debit', 'Borç'), ('credit', 'Alacak')], max_length=10, verbose_name='Hareket yönü')),
                ('transaction_type', models.CharField(choices=[('sales_invoice', 'Satış faturası'), ('collection', 'Tahsilat'), ('manual_debit', 'Manuel borç'), ('manual_credit', 'Manuel alacak'), ('adjustment', 'Bakiye düzeltmesi')], max_length=30, verbose_name='Hareket tipi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('reversed', 'Ters kayıt'), ('cancelled', 'İptal')], default='active', max_length=12, verbose_name='Durum')),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='İşlem tarihi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('reference_number', models.CharField(blank=True, max_length=80, verbose_name='Referans numarası')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.customeraccount', verbose_name='Cari hesap')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_account_transactions', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_account_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_account_transaction', to='sales.invoice', verbose_name='Kaynak satış faturası')),
            ],
            options={
                'verbose_name': 'Cari hesap hareketi',
                'verbose_name_plural': 'Cari hesap hareketleri',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['company', 'customer'], name='finance_cus_company_4ab631_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccount',
            index=models.Index(fields=['company', 'is_active'], name='finance_cus_company_5b4723_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.UniqueConstraint(fields=('company', 'customer', 'currency'), name='unique_customer_account_per_currency'),
        ),
        migrations.AddIndex(
            model_name='customeraccounttransaction',
            index=models.Index(fields=['company', 'transaction_date'], name='finance_cus_company_266169_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccounttransaction',
            index=models.Index(fields=['account', 'status'], name='finance_cus_account_4f4922_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccounttransaction',
            index=models.Index(fields=['company', 'transaction_type'], name='finance_cus_company_d09c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='customeraccounttransaction',
            index=models.Index(fields=['due_date', 'status'], name='finance_cus_due_dat_8b75a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='customeraccounttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_account_transaction_amount_positive'),
        ),
    ]
