# Generated by Django 6.0.7 on 2026-07-29 19:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Hesap adı')),
                ('account_type', models.CharField(choices=[('cash', 'Kasa'), ('bank', 'Banka')], max_length=10, verbose_name='Hesap tipi')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='Banka adı')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Kasa / banka hesabı',
                'verbose_name_plural': 'Kasa / banka hesapları',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccountTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış')], max_length=5, verbose_name='Hareket yönü')),
                ('transaction_type', models.CharField(choices=[('collection', 'Tahsilat'), ('payment', 'Ödeme'), ('manual_in', 'Manuel giriş'), ('manual_out', 'Manuel çıkış')], max_length=20, verbose_name='Hareket tipi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('reversed', 'Ters kayıt'), ('cancelled', 'İptal')], default='active', max_length=12, verbose_name='Durum')),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='İşlem tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('reference_number', models.CharField(blank=True, max_length=80, verbose_name='Referans numarası')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialaccount', verbose_name='Kasa / banka hesabı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_account_transactions', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_account_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('customer_account_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_account_transaction', to='finance.customeraccounttransaction', verbose_name='Bağlı cari hareket')),
            ],
            options={
                'verbose_name': 'Kasa / banka hareketi',
                'verbose_name_plural': 'Kasa / banka hareketleri',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'currency'), name='unique_financial_account_name_per_currency'),
        ),
        migrations.AddIndex(
            model_name='financialaccounttransaction',
            index=models.Index(fields=['company', 'transaction_date'], name='finance_fin_company_f693f5_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccounttransaction',
            index=models.Index(fields=['account', 'status'], name='finance_fin_account_49e418_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialaccounttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_account_transaction_amount_positive'),
        ),
    ]
