# Generated by Django 6.0.7 on 2026-07-30 09:08

import apps.finance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialaccount_financialaccounttransaction_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_number', models.CharField(default=apps.finance.models.generate_payment_plan_number, editable=False, max_length=30, unique=True, verbose_name='Plan numarası')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Toplam tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('installment_count', models.PositiveSmallIntegerField(verbose_name='Taksit sayısı')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='draft', max_length=12, verbose_name='Durum')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='finance.customeraccount', verbose_name='Cari hesap')),
            ],
            options={
                'verbose_name': 'Ödeme planı',
                'verbose_name_plural': 'Ödeme planları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveSmallIntegerField(verbose_name='Taksit sıra numarası')),
                ('due_date', models.DateField(verbose_name='Vade tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Taksit tutarı')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('partially_paid', 'Kısmi tahsil edildi'), ('paid', 'Tahsil edildi'), ('overdue', 'Vadesi geçti'), ('cancelled', 'İptal')], default='pending', max_length=20, verbose_name='Durum')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='finance.paymentplan', verbose_name='Ödeme planı')),
            ],
            options={
                'verbose_name': 'Ödeme planı taksiti',
                'verbose_name_plural': 'Ödeme planı taksitleri',
                'ordering': ['due_date', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Eşleştirilen tutar')),
                ('collection_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plan_allocations', to='finance.customeraccounttransaction', verbose_name='Tahsilat hareketi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_plan_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.paymentplaninstallment', verbose_name='Taksit')),
            ],
            options={
                'verbose_name': 'Tahsilat eşleştirmesi',
                'verbose_name_plural': 'Tahsilat eşleştirmeleri',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['company', 'status'], name='finance_pay_company_95c536_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['customer_account', 'status'], name='finance_pay_custome_40c2a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='payment_plan_total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentplan',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gt', 0)), name='payment_plan_installment_count_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentplaninstallment',
            index=models.Index(fields=['due_date', 'status'], name='finance_pay_due_dat_3d8615_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplaninstallment',
            index=models.Index(fields=['payment_plan', 'status'], name='finance_pay_payment_1dc88a_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentplaninstallment',
            constraint=models.UniqueConstraint(fields=('payment_plan', 'installment_number'), name='unique_payment_plan_installment_number'),
        ),
        migrations.AddConstraint(
            model_name='paymentplaninstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_plan_installment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentplanallocation',
            constraint=models.UniqueConstraint(fields=('installment', 'collection_transaction'), name='unique_installment_collection_allocation'),
        ),
        migrations.AddConstraint(
            model_name='paymentplanallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_plan_allocation_amount_positive'),
        ),
    ]
