# Generated by Django 6.0.7 on 2026-07-30 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentplan_paymentplaninstallment_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAIAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Analiz bekliyor'), ('processing', 'Analiz ediliyor'), ('completed', 'Analiz tamamlandı'), ('failed', 'Analiz başarısız')], default='pending', max_length=12, verbose_name='AI analiz durumu')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Finans veri özeti')),
                ('executive_summary', models.TextField(blank=True, verbose_name='Yönetici özeti')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], max_length=10, verbose_name='Risk seviyesi')),
                ('risks', models.JSONField(blank=True, default=list, verbose_name='Tespit edilen riskler')),
                ('recommended_actions', models.JSONField(blank=True, default=list, verbose_name='Önerilen aksiyonlar')),
                ('ai_error', models.TextField(blank=True, verbose_name='AI analiz hatası')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_ai_analyses', to='organizations.company', verbose_name='Şirket')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_finance_ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Analizi isteyen kullanıcı')),
            ],
            options={
                'verbose_name': 'Finans AI analizi',
                'verbose_name_plural': 'Finans AI analizleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='finance_fin_company_5eb432_idx')],
            },
        ),
    ]
