# Generated by Django 6.0.7 on 2026-07-30 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financeaianalysis'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Yeni Finans Sohbeti', max_length=160, verbose_name='Sohbet başlığı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_ai_conversations', to='organizations.company', verbose_name='Şirket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Finans AI sohbeti',
                'verbose_name_plural': 'Finans AI sohbetleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Kullanıcı'), ('assistant', 'Finans AI')], max_length=12, verbose_name='Mesaj sahibi')),
                ('content', models.TextField(verbose_name='Mesaj içeriği')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'Yanıt hazırlanıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='completed', max_length=12, verbose_name='Yanıt durumu')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Kullanılan finans bağlamı')),
                ('ai_error', models.TextField(blank=True, verbose_name='AI yanıt hatası')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='finance.financeaiconversation', verbose_name='Sohbet')),
            ],
            options={
                'verbose_name': 'Finans AI mesajı',
                'verbose_name_plural': 'Finans AI mesajları',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financeaiconversation',
            index=models.Index(fields=['company', 'user', 'is_active'], name='finance_fin_company_12b744_idx'),
        ),
        migrations.AddIndex(
            model_name='financeaimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='finance_fin_convers_61c0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='financeaimessage',
            index=models.Index(fields=['role', 'status'], name='finance_fin_role_349407_idx'),
        ),
    ]
