# Generated by Django 6.0.7 on 2026-07-31 12:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financeaiconversation_financeaimessage_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBudget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Bütçe adı')),
                ('fiscal_year', models.PositiveSmallIntegerField(verbose_name='Mali yıl')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para birimi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('closed', 'Kapandı')], default='draft', max_length=12, verbose_name='Durum')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_budgets', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
            ],
            options={
                'verbose_name': 'Finans bütçesi',
                'verbose_name_plural': 'Finans bütçeleri',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceBudgetLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.DateField(verbose_name='Bütçe ayı')),
                ('category', models.CharField(max_length=100, verbose_name='Bütçe kalemi')),
                ('planned_inflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Planlanan nakit girişi')),
                ('planned_outflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Planlanan nakit çıkışı')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.financebudget', verbose_name='Bütçe')),
            ],
            options={
                'verbose_name': 'Finans bütçe satırı',
                'verbose_name_plural': 'Finans bütçe satırları',
                'ordering': ['period_month', 'category'],
            },
        ),
        migrations.AddIndex(
            model_name='financebudget',
            index=models.Index(fields=['company', 'fiscal_year', 'status'], name='finance_fin_company_269f03_idx'),
        ),
        migrations.AddConstraint(
            model_name='financebudget',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'fiscal_year'), name='unique_finance_budget_name_per_year'),
        ),
        migrations.AddIndex(
            model_name='financebudgetline',
            index=models.Index(fields=['budget', 'period_month'], name='finance_fin_budget__afebd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'period_month', 'category'), name='unique_finance_budget_line_per_month'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.CheckConstraint(condition=models.Q(('planned_inflow__gt', 0), ('planned_outflow__gt', 0), _connector='OR'), name='finance_budget_line_has_planned_amount'),
        ),
    ]
