# Generated by Django 6.0.7 on 2026-08-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_financebudget_financebudgetline_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financebudget',
            name='revision_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Revizyon numarası'),
        ),
        migrations.AddField(
            model_name='financebudget',
            name='source_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='finance.financebudget', verbose_name='Kaynak bütçe'),
        ),
        migrations.AddConstraint(
            model_name='financebudget',
            constraint=models.UniqueConstraint(fields=('source_budget', 'revision_number'), name='unique_finance_budget_revision'),
        ),
    ]
