# Generated by Django 6.0.7 on 2026-08-01 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_financebudget_revision_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financebudget',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı'),
        ),
        migrations.AddField(
            model_name='financebudget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_finance_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan kullanıcı'),
        ),
        migrations.AddField(
            model_name='financebudget',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onaya gönderim zamanı'),
        ),
        migrations.AddField(
            model_name='financebudget',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_finance_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Onaya gönderen kullanıcı'),
        ),
        migrations.AlterField(
            model_name='financebudget',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('pending_approval', 'Onay bekliyor'), ('active', 'Aktif'), ('closed', 'Kapandı')], default='draft', max_length=20, verbose_name='Durum'),
        ),
    ]
