# Generated by Django 6.0.7 on 2026-08-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financebudget_approved_at_financebudget_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financebudget',
            name='return_reason',
            field=models.TextField(blank=True, verbose_name='Taslağa iade gerekçesi'),
        ),
        migrations.AddField(
            model_name='financebudget',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Taslağa iade zamanı'),
        ),
        migrations.AddField(
            model_name='financebudget',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_finance_budgets', to=settings.AUTH_USER_MODEL, verbose_name='Taslağa iade eden kullanıcı'),
        ),
    ]
