# Generated by Django 6.0.7 on 2026-08-01 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financebudget_return_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBudgetWorkflowEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Oluşturuldu'), ('submitted', 'Onaya gönderildi'), ('approved', 'Onaylandı'), ('returned', 'Taslağa iade edildi'), ('closed', 'Kapatıldı'), ('revision_created', 'Revizyon oluşturuldu')], max_length=20, verbose_name='İşlem')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Önceki durum')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='Yeni durum')),
                ('note', models.TextField(blank=True, verbose_name='İşlem notu')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_budget_workflow_events', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi yapan')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='finance.financebudget', verbose_name='Bütçe')),
            ],
            options={
                'verbose_name': 'Bütçe işlem geçmişi',
                'verbose_name_plural': 'Bütçe işlem geçmişi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['budget', 'created_at'], name='finance_fin_budget__79446c_idx'), models.Index(fields=['budget', 'action'], name='finance_fin_budget__58da7e_idx')],
            },
        ),
    ]
