# Generated by Django 6.0.7 on 2026-08-01 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_financebudgetworkflowevent'),
        ('organizations', '0003_company_tax_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceBudgetAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, verbose_name='Bütçe hesap kodu')),
                ('name', models.CharField(max_length=120, verbose_name='Bütçe hesap adı')),
                ('account_type', models.CharField(choices=[('revenue', 'Gelir'), ('expense', 'Gider')], max_length=12, verbose_name='Hesap türü')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_budget_accounts', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Finans bütçe hesabı',
                'verbose_name_plural': 'Finans bütçe hesapları',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='financebudgetline',
            name='budget_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.financebudgetaccount', verbose_name='Bütçe kontrol hesabı'),
        ),
        migrations.AddField(
            model_name='financialaccounttransaction',
            name='budget_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='finance.financebudgetaccount', verbose_name='Bütçe kontrol hesabı'),
        ),
        migrations.AddIndex(
            model_name='financebudgetaccount',
            index=models.Index(fields=['company', 'account_type', 'is_active'], name='finance_fin_company_51f137_idx'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetaccount',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_finance_budget_account_code'),
        ),
    ]
