# Generated by Django 6.0.7 on 2026-08-01 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_backfill_budget_accounts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financebudgetline',
            name='unique_finance_budget_line_per_month',
        ),
        migrations.AlterField(
            model_name='financebudgetline',
            name='budget_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.financebudgetaccount', verbose_name='Bütçe kontrol hesabı'),
        ),
        migrations.AddConstraint(
            model_name='financebudgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'period_month', 'budget_account'), name='unique_budget_account_line_per_month'),
        ),
    ]
