# Generated by Django 6.0.7 on 2026-07-27 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0002_companysubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=180, verbose_name='Konu')),
                ('description', models.TextField(verbose_name='Talep açıklaması')),
                ('category', models.CharField(choices=[('general', 'Genel'), ('sales', 'Satış'), ('inventory', 'Stok'), ('manufacturing', 'Üretim'), ('account', 'Hesap ve çalışma alanı'), ('billing', 'Plan ve faturalama')], default='general', max_length=30, verbose_name='Kategori')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'İnceleniyor'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='new', max_length=20, verbose_name='Talep durumu')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Çözüm notları')),
                ('ai_status', models.CharField(choices=[('pending', 'Analiz bekliyor'), ('processing', 'Analiz ediliyor'), ('completed', 'Analiz tamamlandı'), ('failed', 'Analiz başarısız')], default='pending', max_length=20, verbose_name='AI analiz durumu')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI özeti')),
                ('ai_category', models.CharField(blank=True, max_length=30, verbose_name='AI kategori önerisi')),
                ('ai_priority', models.CharField(blank=True, max_length=20, verbose_name='AI öncelik önerisi')),
                ('ai_suggested_response', models.TextField(blank=True, verbose_name='AI ilk çözüm önerisi')),
                ('ai_error', models.TextField(blank=True, verbose_name='AI analiz hatası')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Atanan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Talebi oluşturan kullanıcı')),
            ],
            options={
                'verbose_name': 'Destek talebi',
                'verbose_name_plural': 'Destek talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
