from django.urls import path

from .views import (
    customer_accounts,
    finance_section,
    home,
    customer_account_collection,
    customer_account_detail,
    cash_bank_accounts,
    cash_bank_account_detail,
    payment_plans,
    payment_plan_detail,
    payment_plan_allocation_create,
    cash_flow,
    finance_ai_analysis_create,
    finance_ai_chat_send,
    finance_ai_chat_message_status,
    budget_reports,
    budget_detail,
    budget_status_update,
    budget_revision_create,
    budget_line_delete,
    budget_line_edit,
    budget_return_to_draft,
    budget_revision_compare,
)


app_name = "finance"

urlpatterns = [
    path("", home, name="home"),
    path(
        "cari-hesaplar/",
        customer_accounts,
        name="customer_accounts",
    ),
    path(
        "cari-hesaplar/<uuid:account_id>/",
        customer_account_detail,
        name="customer_account_detail",
    ),
    path(
        "cari-hesaplar/<uuid:account_id>/tahsilat/",
        customer_account_collection,
        name="customer_account_collection",
    ),
    path(
        "kasa-banka/",
        cash_bank_accounts,
        name="cash_bank_accounts",
    ),
    path(
        "kasa-banka/<uuid:account_id>/",
        cash_bank_account_detail,
        name="cash_bank_account_detail",
    ),
    path(
        "odeme-planlari/",
        payment_plans,
        name="payment_plans",
    ),
    path(
        "odeme-planlari/<uuid:plan_id>/",
        payment_plan_detail,
        name="payment_plan_detail",
    ),
    path(
        "odeme-planlari/<uuid:plan_id>/eslestirme/",
        payment_plan_allocation_create,
        name="payment_plan_allocation_create",
    ),
    path(
        "ai-analiz/",
        finance_ai_analysis_create,
        name="finance_ai_analysis_create",
    ),
    path(
        "ai-sohbet/gonder/",
        finance_ai_chat_send,
        name="finance_ai_chat_send",
    ),
    path(
    "ai-sohbet/mesaj/<uuid:message_id>/durum/",
    finance_ai_chat_message_status,
    name="finance_ai_chat_message_status",
    ),
    path(
        "nakit-akisi/",
        cash_flow,
        name="cash_flow",
    ),
    path(
        "butce-raporlar/",
        budget_reports,
        name="budget_reports",
    ),
    path(
        "butce-raporlar/<uuid:budget_id>/",
        budget_detail,
        name="budget_detail",
    ),
    path(
        "butce-raporlar/<uuid:budget_id>/satirlar/<uuid:line_id>/duzenle/",
        budget_line_edit,
        name="budget_line_edit",
    ),
    path(
        "butce-raporlar/<uuid:budget_id>/satirlar/<uuid:line_id>/sil/",
        budget_line_delete,
        name="budget_line_delete",
    ),
    path(
    "butce-raporlar/<uuid:budget_id>/revizyon-karsilastir/",
    budget_revision_compare,
    name="budget_revision_compare",
),
    path(
        "butce-raporlar/<uuid:budget_id>/revizyon-olustur/",
        budget_revision_create,
        name="budget_revision_create",
    ),
        path(
        "butce-raporlar/<uuid:budget_id>/taslaga-iade/",
        budget_return_to_draft,
        name="budget_return_to_draft",
    ),
    path(
        "butce-raporlar/<uuid:budget_id>/durum/",
        budget_status_update,
        name="budget_status_update",
    ),
    path(
        "<slug:section>/",
        finance_section,
        name="section",
    ),
]