# Generated by Django 6.0.7 on 2026-07-27 07:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, verbose_name='Stok kodu')),
                ('name', models.CharField(max_length=180, verbose_name='Ürün adı')),
                ('product_type', models.CharField(choices=[('raw_material', 'Hammadde'), ('packaging', 'Ambalaj'), ('finished_good', 'Bitmiş ürün'), ('service', 'Hizmet')], default='raw_material', max_length=20, verbose_name='Ürün tipi')),
                ('unit', models.CharField(default='adet', max_length=20, verbose_name='Birim')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Yeniden sipariş seviyesi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=80, verbose_name='Lot numarası')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Mevcut miktar')),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Rezerve miktar')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son kullanma tarihi')),
                ('status', models.CharField(choices=[('available', 'Kullanılabilir'), ('quarantined', 'Karantinada'), ('expired', 'Miadı dolmuş'), ('blocked', 'Bloke')], default='available', max_length=20, verbose_name='Lot durumu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Stok lotu',
                'verbose_name_plural': 'Stok lotları',
                'ordering': ['expiry_date', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, verbose_name='Depo kodu')),
                ('name', models.CharField(max_length=120, verbose_name='Depo adı')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='Konum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('receipt', 'Mal kabul'), ('issue', 'Tüketim / çıkış'), ('reservation', 'Rezervasyon'), ('release', 'Rezervasyon çözme'), ('adjustment', 'Sayım düzeltmesi')], max_length=20, verbose_name='Hareket tipi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Miktar')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Birim maliyet')),
                ('reference', models.CharField(blank=True, help_text='Örn. üretim emri veya satın alma siparişi numarası', max_length=100, verbose_name='Referans')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.inventorylot', verbose_name='Lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product', verbose_name='Ürün')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.warehouse', verbose_name='Depo')),
            ],
            options={
                'verbose_name': 'Stok hareketi',
                'verbose_name_plural': 'Stok hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.warehouse', verbose_name='Depo'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'product_type'], name='inventory_p_company_b66a23_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='inventory_p_company_e5d498_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='unique_product_sku_per_company'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_warehouse_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'created_at'], name='inventory_s_warehou_f752ce_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_5919a9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['warehouse', 'status'], name='inventory_i_warehou_8657c3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['product', 'status'], name='inventory_i_product_5f0afe_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'lot_number'), name='unique_lot_per_product_warehouse'),
        ),
    ]
