# Generated by Django 6.0.7 on 2026-07-27 06:55

import apps.manufacturing.models
import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('sales', '0002_salesorder_salesorderline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_number', models.CharField(default=apps.manufacturing.models.generate_production_number, editable=False, max_length=30, unique=True, verbose_name='Üretim emri numarası')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('in_production', 'Üretimde'), ('quality_control', 'Kalite Kontrolde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='planned', max_length=20, verbose_name='Durum')),
                ('planned_start_date', models.DateField(default=datetime.date.today, verbose_name='Planlanan başlangıç')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='Planlanan tamamlanma')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Gerçek tamamlanma')),
                ('notes', models.TextField(blank=True, verbose_name='Üretim notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='organizations.company', verbose_name='Şirket')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu kullanıcı')),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_order', to='sales.salesorder', verbose_name='Kaynak satış siparişi')),
            ],
            options={
                'verbose_name': 'Üretim emri',
                'verbose_name_plural': 'Üretim emirleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Üretilecek ürün veya işlem')),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Planlanan miktar')),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tamamlanan miktar')),
                ('line_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.productionorder', verbose_name='Üretim emri')),
            ],
            options={
                'verbose_name': 'Üretim emri kalemi',
                'verbose_name_plural': 'Üretim emri kalemleri',
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company', 'status'], name='manufacturi_company_d2e705_idx'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company', 'sales_order'], name='manufacturi_company_2ba701_idx'),
        ),
    ]
