# Generated by Django 6.0.7 on 2026-07-27 07:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Reçete versiyonu')),
                ('yield_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Reçete çıktı miktarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Üretim talimatları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_of_material', to='organizations.company', verbose_name='Şirket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_of_material', to='inventory.product', verbose_name='Bitmiş ürün')),
            ],
            options={
                'verbose_name': 'Ürün reçetesi',
                'verbose_name_plural': 'Ürün reçeteleri',
                'ordering': ['product__name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Birim başına miktar')),
                ('scrap_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Fire oranı (%)')),
                ('line_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.billofmaterial', verbose_name='Reçete')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='inventory.product', verbose_name='Bileşen')),
            ],
            options={
                'verbose_name': 'Reçete kalemi',
                'verbose_name_plural': 'Reçete kalemleri',
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='billofmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_bom_version_per_product'),
        ),
        migrations.AddConstraint(
            model_name='billofmaterialline',
            constraint=models.UniqueConstraint(fields=('bill_of_material', 'component'), name='unique_component_per_bom'),
        ),
    ]
