# Generated by Django 6.0.7 on 2026-07-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('manufacturing', '0002_billofmaterial_billofmaterialline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_order_lines', to='inventory.product', verbose_name='Ürün kartı'),
        ),
    ]
