# Generated by Django 6.0.7 on 2026-07-27 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_productionorderline_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Sonuç bekleniyor'), ('passed', 'Geçti'), ('conditional', 'Şartlı geçti'), ('failed', 'Kaldı')], default='pending', max_length=20, verbose_name='Kontrol sonucu')),
                ('sample_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kontrol edilen numune miktarı')),
                ('notes', models.TextField(blank=True, verbose_name='Kalite kontrol notları')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='Kontrol tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Kontrolü yapan kullanıcı')),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspection', to='manufacturing.productionorder', verbose_name='Üretim emri')),
            ],
            options={
                'verbose_name': 'Kalite kontrol kaydı',
                'verbose_name_plural': 'Kalite kontrol kayıtları',
            },
        ),
    ]
