# Generated by Django 6.0.7 on 2026-07-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_qualityinspection'),
        ('organizations', '0002_companysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='organizations.branch', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='organizations.department', verbose_name='Departman'),
        ),
    ]
