# Generated by Django 6.0.7 on 2026-07-25 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180, verbose_name='Müşteri adı')),
                ('customer_type', models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], default='corporate', max_length=20, verbose_name='Müşteri tipi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('tax_number', models.CharField(blank=True, max_length=30, verbose_name='Vergi numarası')),
                ('status', models.CharField(choices=[('lead', 'Potansiyel'), ('active', 'Aktif'), ('inactive', 'Pasif')], default='lead', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='crm_custome_company_0e3ebf_idx'), models.Index(fields=['company', 'name'], name='crm_custome_company_0f6d0d_idx')],
            },
        ),
    ]
