# Generated by Django 6.0.7 on 2026-07-26 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180, verbose_name='Fırsat adı')),
                ('stage', models.CharField(choices=[('lead', 'Yeni Fırsat'), ('contacted', 'İletişime Geçildi'), ('proposal', 'Teklif Hazırlandı'), ('negotiation', 'Müzakere'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi')], default='lead', max_length=20, verbose_name='Aşama')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Tahmini tutar')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Beklenen kapanış tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Satış fırsatı',
                'verbose_name_plural': 'Satış fırsatları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='crm_custome_company_0e3ebf_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='crm_custome_company_0f6d0d_idx',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organizations.company', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.customer', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu kullanıcı'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'stage'], name='crm_opportu_company_1121c7_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company', 'customer'], name='crm_opportu_company_919687_idx'),
        ),
    ]
