# Generated by Django 6.0.7 on 2026-07-26 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_opportunity_alter_customer_options_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'status'], name='crm_custome_company_0e3ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'name'], name='crm_custome_company_0f6d0d_idx'),
        ),
    ]
