# Generated by Django 6.0.7 on 2026-07-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='labels',
            field=models.CharField(blank=True, help_text='Örn. ERP, CRM, Üretim', max_length=160, verbose_name='Etiketler'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son iletişim tarihi'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='priority',
            field=models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10, verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='quote_status',
            field=models.CharField(choices=[('not_started', 'Teklif bekliyor'), ('draft', 'Taslak hazırlanıyor'), ('sent', 'Teklif gönderildi'), ('accepted', 'Teklif onaylandı')], default='not_started', max_length=20, verbose_name='Teklif durumu'),
        ),
    ]
