# Generated by Django 6.0.7 on 2026-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_opportunity_labels_opportunity_last_contacted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Fatura adresi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_office',
            field=models.CharField(blank=True, max_length=120, verbose_name='Vergi dairesi'),
        ),
    ]
