# Generated by Django 6.0.7 on 2026-08-03 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('employee_number', models.CharField(max_length=30, verbose_name='Personel numarası')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('preferred_name', models.CharField(blank=True, max_length=100, verbose_name='Tercih edilen ad')),
                ('work_email', models.EmailField(blank=True, max_length=254, verbose_name='Kurumsal e-posta')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Kişisel e-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum tarihi')),
                ('hire_date', models.DateField(verbose_name='İşe giriş tarihi')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='İşten ayrılma tarihi')),
                ('employment_status', models.CharField(choices=[('active', 'Aktif'), ('on_leave', 'İzinli'), ('suspended', 'Askıda'), ('terminated', 'İşten ayrıldı')], default='active', max_length=20, verbose_name='Çalışma durumu')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.company', verbose_name='Şirket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı hesabı')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'ordering': ['company__name', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('code', models.CharField(max_length=30, verbose_name='Pozisyon kodu')),
                ('title', models.CharField(max_length=150, verbose_name='Pozisyon adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_positions', to='organizations.company', verbose_name='Şirket')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hr_positions', to='organizations.department', verbose_name='Departman')),
            ],
            options={
                'verbose_name': 'Pozisyon',
                'verbose_name_plural': 'Pozisyonlar',
                'ordering': ['company__name', 'department__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employment_type', models.CharField(choices=[('full_time', 'Tam zamanlı'), ('part_time', 'Yarı zamanlı'), ('contractor', 'Sözleşmeli'), ('intern', 'Stajyer')], default='full_time', max_length=20, verbose_name='Çalışma türü')),
                ('start_date', models.DateField(verbose_name='Başlangıç tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş tarihi')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Birincil atama')),
                ('is_department_manager', models.BooleanField(default=False, verbose_name='Departman yöneticisi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organizations.branch', verbose_name='Şube')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organizations.department', verbose_name='Departman')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.employee', verbose_name='Personel')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_report_assignments', to='hr.employee', verbose_name='Bağlı yönetici')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='hr.position', verbose_name='Pozisyon')),
            ],
            options={
                'verbose_name': 'Personel ataması',
                'verbose_name_plural': 'Personel atamaları',
                'ordering': ['-is_primary', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'employment_status', 'is_active'], name='hr_employee_company_80d948_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'last_name', 'first_name'], name='hr_employee_company_7ae5e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_number'), name='unique_employee_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('company', 'user'), name='unique_employee_user_per_company'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company', 'department', 'is_active'], name='hr_position_company_2d2f3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_hr_position_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='employmentassignment',
            index=models.Index(fields=['branch', 'department', 'end_date'], name='hr_employme_branch__ae15d8_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentassignment',
            index=models.Index(fields=['position', 'end_date'], name='hr_employme_positio_131dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentassignment',
            index=models.Index(fields=['manager', 'end_date'], name='hr_employme_manager_ff3683_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('employee',), name='unique_active_primary_employee_assignment'),
        ),
        migrations.AddConstraint(
            model_name='employmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_department_manager', True)), fields=('department',), name='unique_active_department_manager'),
        ),
    ]
