# Generated by Django 6.0.7 on 2026-08-03 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentAssignmentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('assignment_change', 'Atama değişikliği')], default='assignment_change', max_length=30, verbose_name='Olay türü')),
                ('effective_date', models.DateField(verbose_name='Geçerlilik tarihi')),
                ('reason', models.TextField(verbose_name='Değişiklik gerekçesi')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_assignment_events', to=settings.AUTH_USER_MODEL, verbose_name='Değişikliği yapan')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employment_assignment_events', to='organizations.company', verbose_name='Şirket')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to='hr.employee', verbose_name='Personel')),
                ('new_assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='change_event', to='hr.employmentassignment', verbose_name='Yeni atama')),
                ('previous_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_events', to='hr.employmentassignment', verbose_name='Önceki atama')),
            ],
            options={
                'verbose_name': 'Atama değişiklik kaydı',
                'verbose_name_plural': 'Atama değişiklik kayıtları',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'effective_date'], name='hr_employme_company_087a84_idx'), models.Index(fields=['employee', 'effective_date'], name='hr_employme_employe_840982_idx')],
            },
        ),
    ]
