# Generated by Django 6.0.7 on 2026-08-03 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employmentassignmentevent'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('code', models.CharField(max_length=30, verbose_name='İzin türü kodu')),
                ('name', models.CharField(max_length=150, verbose_name='İzin türü adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Ücretli izin')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Onay gerektirir')),
                ('deducts_balance', models.BooleanField(default=True, verbose_name='Bakiyeden düşer')),
                ('default_entitlement_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Varsayılan hak edilen gün')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_types', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'İzin türü',
                'verbose_name_plural': 'İzin türleri',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Başlangıç tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş tarihi')),
                ('requested_days', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Talep edilen gün')),
                ('reason', models.TextField(verbose_name='Talep gerekçesi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Talep durumu')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme zamanı')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Karar zamanı')),
                ('decision_note', models.TextField(blank=True, verbose_name='Karar notu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_requests', to='organizations.company', verbose_name='Şirket')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_absence_requests', to=settings.AUTH_USER_MODEL, verbose_name='Karar veren kullanıcı')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_requests', to='hr.employee', verbose_name='Personel')),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.absencetype', verbose_name='İzin türü')),
            ],
            options={
                'verbose_name': 'İzin talebi',
                'verbose_name_plural': 'İzin talepleri',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yıl')),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Hak edilen gün')),
                ('carried_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Devreden gün')),
                ('adjustment_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Düzeltme günü')),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Kullanılan gün')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_balances', to='organizations.company', verbose_name='Şirket')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_balances', to='hr.employee', verbose_name='Personel')),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_balances', to='hr.absencetype', verbose_name='İzin türü')),
            ],
            options={
                'verbose_name': 'İzin bakiyesi',
                'verbose_name_plural': 'İzin bakiyeleri',
                'ordering': ['-year', 'employee__last_name', 'employee__first_name', 'absence_type__name'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRequestEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('draft', 'Taslak'), ('submitted', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal edildi')], max_length=20, verbose_name='Önceki durum')),
                ('new_status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal edildi')], max_length=20, verbose_name='Yeni durum')),
                ('note', models.TextField(blank=True, verbose_name='İşlem notu')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_request_events', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi yapan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_request_events', to='organizations.company', verbose_name='Şirket')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.absencerequest', verbose_name='İzin talebi')),
            ],
            options={
                'verbose_name': 'İzin talebi işlem kaydı',
                'verbose_name_plural': 'İzin talebi işlem kayıtları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='hr_absencer_company_476121_idx'), models.Index(fields=['request', 'created_at'], name='hr_absencer_request_aa7e70_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='absencetype',
            index=models.Index(fields=['company', 'is_active'], name='hr_absencet_company_ff3ea7_idx'),
        ),
        migrations.AddConstraint(
            model_name='absencetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_absence_type_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='absencetype',
            constraint=models.CheckConstraint(condition=models.Q(('default_entitlement_days__gte', 0)), name='absence_type_entitlement_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['company', 'status', 'start_date'], name='hr_absencer_company_e9fa6f_idx'),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['employee', 'status', 'start_date'], name='hr_absencer_employe_ea96ba_idx'),
        ),
        migrations.AddIndex(
            model_name='absencerequest',
            index=models.Index(fields=['absence_type', 'start_date'], name='hr_absencer_absence_eae090_idx'),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='absence_request_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='absencerequest',
            constraint=models.CheckConstraint(condition=models.Q(('requested_days__gt', 0)), name='absence_request_days_positive'),
        ),
        migrations.AddIndex(
            model_name='absencebalance',
            index=models.Index(fields=['company', 'year'], name='hr_absenceb_company_8d0d48_idx'),
        ),
        migrations.AddIndex(
            model_name='absencebalance',
            index=models.Index(fields=['employee', 'year'], name='hr_absenceb_employe_2cef25_idx'),
        ),
        migrations.AddConstraint(
            model_name='absencebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'absence_type', 'year'), name='unique_employee_absence_balance_per_year'),
        ),
        migrations.AddConstraint(
            model_name='absencebalance',
            constraint=models.CheckConstraint(condition=models.Q(('entitled_days__gte', 0)), name='absence_balance_entitled_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='absencebalance',
            constraint=models.CheckConstraint(condition=models.Q(('carried_days__gte', 0)), name='absence_balance_carried_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='absencebalance',
            constraint=models.CheckConstraint(condition=models.Q(('used_days__gte', 0)), name='absence_balance_used_nonnegative'),
        ),
    ]
