# Generated by Django 6.0.7 on 2026-08-04 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_absencetype_absencerequest_absencebalance_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('code', models.CharField(max_length=30, verbose_name='Çalışma takvimi kodu')),
                ('name', models.CharField(max_length=150, verbose_name='Çalışma takvimi adı')),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Haftalık çalışma saati')),
                ('timezone_name', models.CharField(default='Europe/Istanbul', max_length=64, verbose_name='Saat dilimi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Çalışma takvimi',
                'verbose_name_plural': 'Çalışma takvimleri',
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Başlangıç tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş tarihi')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Birincil takvim mi?')),
                ('assignment_note', models.TextField(blank=True, verbose_name='Atama notu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_schedule_assignments', to='organizations.company', verbose_name='Şirket')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='hr.employee', verbose_name='Personel')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='hr.workschedule', verbose_name='Çalışma takvimi')),
            ],
            options={
                'verbose_name': 'Personel çalışma takvimi ataması',
                'verbose_name_plural': 'Personel çalışma takvimi atamaları',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Haftanın günü')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='Çalışma günü mü?')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Başlangıç saati')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Bitiş saati')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='Mola süresi (dakika)')),
                ('crosses_midnight', models.BooleanField(default=False, verbose_name='Ertesi güne taşıyor mu?')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='hr.workschedule', verbose_name='Çalışma takvimi')),
            ],
            options={
                'verbose_name': 'Çalışma takvimi günü',
                'verbose_name_plural': 'Çalışma takvimi günleri',
                'ordering': ['work_schedule', 'weekday'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField(verbose_name='Çalışma tarihi')),
                ('scheduled_start_time', models.TimeField(blank=True, null=True, verbose_name='Planlanan başlangıç')),
                ('scheduled_end_time', models.TimeField(blank=True, null=True, verbose_name='Planlanan bitiş')),
                ('clock_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Giriş zamanı')),
                ('clock_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış zamanı')),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='Mola süresi (dakika)')),
                ('worked_minutes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Çalışılan süre (dakika)')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Geç kalma süresi (dakika)')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='Fazla çalışma süresi (dakika)')),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('present', 'Çalıştı'), ('late', 'Geç kaldı'), ('absent', 'Devamsız'), ('on_leave', 'İzinli'), ('remote', 'Uzaktan çalıştı'), ('non_working_day', 'Çalışma dışı gün')], default='scheduled', max_length=30, verbose_name='Devam durumu')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('device', 'Cihaz'), ('import', 'İçe aktarma'), ('system', 'Sistem')], default='manual', max_length=20, verbose_name='Kayıt kaynağı')),
                ('approval_status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20, verbose_name='Onay durumu')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='organizations.company', verbose_name='Şirket')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='hr.employee', verbose_name='Personel')),
                ('schedule_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.employeescheduleassignment', verbose_name='Çalışma takvimi ataması')),
            ],
            options={
                'verbose_name': 'Zaman ve devam kaydı',
                'verbose_name_plural': 'Zaman ve devam kayıtları',
                'ordering': ['-work_date', 'employee__last_name', 'employee__first_name'],
                'indexes': [models.Index(fields=['company', 'work_date', 'status'], name='hr_attendan_company_8e139d_idx'), models.Index(fields=['employee', 'work_date'], name='hr_attendan_employe_6a67b0_idx'), models.Index(fields=['company', 'approval_status', 'work_date'], name='hr_attendan_company_a8b752_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'employee', 'work_date'), name='unique_attendance_record_per_employee_day')],
            },
        ),
        migrations.AddIndex(
            model_name='workschedule',
            index=models.Index(fields=['company', 'is_active'], name='hr_worksche_company_d99d2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_work_schedule_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours__gt', 0)), name='work_schedule_weekly_hours_positive'),
        ),
        migrations.AddIndex(
            model_name='employeescheduleassignment',
            index=models.Index(fields=['company', 'start_date', 'end_date'], name='hr_employee_company_b007fd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeescheduleassignment',
            index=models.Index(fields=['employee', 'is_primary', 'end_date'], name='hr_employee_employe_54be1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeescheduleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='schedule_assignment_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='employeescheduleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('employee',), name='unique_active_primary_schedule_per_employee'),
        ),
        migrations.AddIndex(
            model_name='workscheduleday',
            index=models.Index(fields=['work_schedule', 'weekday'], name='hr_worksche_work_sc_f86699_idx'),
        ),
        migrations.AddConstraint(
            model_name='workscheduleday',
            constraint=models.UniqueConstraint(fields=('work_schedule', 'weekday'), name='unique_weekday_per_work_schedule'),
        ),
    ]
