# Generated by Django 6.0.7 on 2026-08-04 13:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_workschedule_employeescheduleassignment_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecordEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('generated', 'Kayıt üretildi'), ('clock_in', 'Giriş yapıldı'), ('clock_out', 'Çıkış yapıldı'), ('submitted', 'Onaya gönderildi'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('updated', 'Güncellendi')], max_length=30, verbose_name='İşlem türü')),
                ('previous_approval_status', models.CharField(blank=True, choices=[('draft', 'Taslak'), ('submitted', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], max_length=20, verbose_name='Önceki onay durumu')),
                ('new_approval_status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Onay bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], max_length=20, verbose_name='Yeni onay durumu')),
                ('note', models.TextField(blank=True, verbose_name='İşlem notu')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem zamanı')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_record_events', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi yapan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_record_events', to='organizations.company', verbose_name='Şirket')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.attendancerecord', verbose_name='Zaman ve devam kaydı')),
            ],
            options={
                'verbose_name': 'Zaman ve devam işlem kaydı',
                'verbose_name_plural': 'Zaman ve devam işlem kayıtları',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['company', 'occurred_at'], name='hr_attendan_company_1e8627_idx'), models.Index(fields=['record', 'occurred_at'], name='hr_attendan_record__bc38b5_idx'), models.Index(fields=['event_type', 'occurred_at'], name='hr_attendan_event_t_bf1849_idx')],
            },
        ),
    ]
