# Generated by Django 6.0.7 on 2026-08-04 14:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_attendancerecordevent'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviewCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('code', models.CharField(max_length=30, verbose_name='Dönem kodu')),
                ('name', models.CharField(max_length=150, verbose_name='Dönem adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('start_date', models.DateField(verbose_name='Başlangıç tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş tarihi')),
                ('self_review_deadline', models.DateField(blank=True, null=True, verbose_name='Öz değerlendirme son tarihi')),
                ('manager_review_deadline', models.DateField(blank=True, null=True, verbose_name='Yönetici değerlendirmesi son tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('open', 'Açık'), ('closed', 'Kapalı'), ('archived', 'Arşivlendi')], default='draft', max_length=20, verbose_name='Durum')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_review_cycles', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Performans değerlendirme dönemi',
                'verbose_name_plural': 'Performans değerlendirme dönemleri',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('self_review', 'Öz değerlendirmede'), ('manager_review', 'Yönetici değerlendirmesinde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal edildi')], default='draft', max_length=30, verbose_name='Durum')),
                ('employee_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Çalışan öz değerlendirme puanı')),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Yönetici puanı')),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Genel performans puanı')),
                ('employee_comment', models.TextField(blank=True, verbose_name='Çalışan değerlendirme notu')),
                ('manager_comment', models.TextField(blank=True, verbose_name='Yönetici değerlendirme notu')),
                ('development_plan', models.TextField(blank=True, verbose_name='Gelişim planı')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma zamanı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='organizations.company', verbose_name='Şirket')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Tamamlayan kullanıcı')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='hr.employee', verbose_name='Değerlendirilen personel')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_performance_reviews', to='hr.employee', verbose_name='Değerlendiren yönetici')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_reviews', to='hr.performancereviewcycle', verbose_name='Değerlendirme dönemi')),
            ],
            options={
                'verbose_name': 'Performans değerlendirmesi',
                'verbose_name_plural': 'Performans değerlendirmeleri',
                'ordering': ['-cycle__start_date', 'employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGoal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Hedef başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Hedef açıklaması')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ağırlık yüzdesi')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Hedef değer')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Mevcut değer')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Ölçü birimi')),
                ('start_date', models.DateField(verbose_name='Başlangıç tarihi')),
                ('due_date', models.DateField(verbose_name='Hedef tarihi')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='İlerleme yüzdesi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('in_progress', 'Devam ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('completion_note', models.TextField(blank=True, verbose_name='Tamamlama notu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_goals', to='organizations.company', verbose_name='Şirket')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_goals', to='hr.employee', verbose_name='Personel')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_goals', to='hr.performancereviewcycle', verbose_name='Değerlendirme dönemi')),
            ],
            options={
                'verbose_name': 'Personel hedefi',
                'verbose_name_plural': 'Personel hedefleri',
                'ordering': ['due_date', 'employee__last_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Oluşturuldu'), ('self_review_started', 'Öz değerlendirme başladı'), ('self_review_submitted', 'Öz değerlendirme gönderildi'), ('manager_review_started', 'Yönetici değerlendirmesi başladı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal edildi'), ('updated', 'Güncellendi')], max_length=40, verbose_name='İşlem türü')),
                ('previous_status', models.CharField(blank=True, choices=[('draft', 'Taslak'), ('self_review', 'Öz değerlendirmede'), ('manager_review', 'Yönetici değerlendirmesinde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal edildi')], max_length=30, verbose_name='Önceki durum')),
                ('new_status', models.CharField(choices=[('draft', 'Taslak'), ('self_review', 'Öz değerlendirmede'), ('manager_review', 'Yönetici değerlendirmesinde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal edildi')], max_length=30, verbose_name='Yeni durum')),
                ('note', models.TextField(blank=True, verbose_name='İşlem notu')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem zamanı')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_review_events', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi yapan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_review_events', to='organizations.company', verbose_name='Şirket')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.performancereview', verbose_name='Performans değerlendirmesi')),
            ],
            options={
                'verbose_name': 'Performans değerlendirme işlem kaydı',
                'verbose_name_plural': 'Performans değerlendirme işlem kayıtları',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='performancereviewcycle',
            index=models.Index(fields=['company', 'status', 'start_date'], name='hr_performa_company_d2e150_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancereviewcycle',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_performance_cycle_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='performancereviewcycle',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='performance_cycle_end_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['company', 'cycle', 'status'], name='hr_performa_company_15044b_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', 'status'], name='hr_performa_employe_c5c3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['manager', 'status'], name='hr_performa_manager_6255ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('company', 'cycle', 'employee'), name='unique_performance_review_per_cycle_employee'),
        ),
        migrations.AddIndex(
            model_name='employeegoal',
            index=models.Index(fields=['company', 'cycle', 'status'], name='hr_employee_company_090ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegoal',
            index=models.Index(fields=['employee', 'status', 'due_date'], name='hr_employee_employe_392575_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeegoal',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee', 'title'), name='unique_goal_title_per_cycle_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeegoal',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='employee_goal_weight_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='employeegoal',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='employee_goal_progress_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='employeegoal',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('start_date'))), name='employee_goal_due_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='performancereviewevent',
            index=models.Index(fields=['company', 'occurred_at'], name='hr_performa_company_4e74a4_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereviewevent',
            index=models.Index(fields=['review', 'occurred_at'], name='hr_performa_review__4c723f_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereviewevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='hr_performa_event_t_3c65cb_idx'),
        ),
    ]
