# Generated by Django 6.0.7 on 2026-08-04 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_performancereviewcycle_performancereview_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn profili')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portföy bağlantısı')),
                ('source', models.CharField(choices=[('career_site', 'Kariyer sitesi'), ('linkedin', 'LinkedIn'), ('referral', 'Çalışan referansı'), ('agency', 'İşe alım ajansı'), ('university', 'Üniversite'), ('manual', 'Manuel kayıt'), ('other', 'Diğer')], default='manual', max_length=30, verbose_name='Aday kaynağı')),
                ('current_title', models.CharField(blank=True, max_length=150, verbose_name='Mevcut unvan')),
                ('current_company', models.CharField(blank=True, max_length=150, verbose_name='Mevcut şirket')),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Deneyim yılı')),
                ('resume', models.FileField(blank=True, null=True, upload_to='hr/candidates/resumes/%Y/%m/', verbose_name='Öz geçmiş')),
                ('notes', models.TextField(blank=True, verbose_name='Aday notları')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Kişisel veri işleme onayı')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
            ],
            options={
                'verbose_name': 'Aday',
                'verbose_name_plural': 'Adaylar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(max_length=30, verbose_name='Talep numarası')),
                ('title', models.CharField(max_length=180, verbose_name='İlan başlığı')),
                ('description', models.TextField(verbose_name='İş tanımı')),
                ('requirements', models.TextField(blank=True, verbose_name='Aranan nitelikler')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tam zamanlı'), ('part_time', 'Yarı zamanlı'), ('contract', 'Sözleşmeli'), ('intern', 'Stajyer'), ('temporary', 'Geçici')], default='full_time', max_length=20, verbose_name='İstihdam türü')),
                ('opening_reason', models.CharField(choices=[('new_position', 'Yeni pozisyon'), ('replacement', 'Yerine işe alım'), ('growth', 'Büyüme'), ('temporary_need', 'Geçici ihtiyaç'), ('other', 'Diğer')], default='new_position', max_length=30, verbose_name='Açılma nedeni')),
                ('headcount', models.PositiveSmallIntegerField(default=1, verbose_name='Kontenjan')),
                ('filled_headcount', models.PositiveSmallIntegerField(default=0, verbose_name='Doldurulan kontenjan')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending_approval', 'Onay bekliyor'), ('open', 'Yayında'), ('on_hold', 'Beklemede'), ('filled', 'Pozisyon dolduruldu'), ('cancelled', 'İptal edildi'), ('closed', 'Kapalı')], default='draft', max_length=30, verbose_name='Durum')),
                ('target_start_date', models.DateField(blank=True, null=True, verbose_name='Hedef işe başlangıç tarihi')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Son başvuru tarihi')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayınlanma zamanı')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanma zamanı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requisitions', to='organizations.company', verbose_name='Şirket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requisitions', to='organizations.department', verbose_name='Departman')),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_job_requisitions', to='hr.employee', verbose_name='İşe alım yöneticisi')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requisitions', to='hr.position', verbose_name='Pozisyon')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruiter_job_requisitions', to='hr.employee', verbose_name='İK sorumlusu')),
            ],
            options={
                'verbose_name': 'İşe alım talebi',
                'verbose_name_plural': 'İşe alım talepleri',
                'ordering': ['-created_at', 'requisition_number'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('applied', 'Başvurdu'), ('screening', 'Ön eleme'), ('phone_screen', 'Telefon görüşmesi'), ('interview', 'Mülakat'), ('assessment', 'Değerlendirme'), ('offer', 'Teklif'), ('hired', 'İşe alındı'), ('rejected', 'Reddedildi'), ('withdrawn', 'Aday geri çekildi')], default='applied', max_length=30, verbose_name='Pipeline aşaması')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('hired', 'İşe alındı'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri çekildi'), ('archived', 'Arşivlendi')], default='active', max_length=20, verbose_name='Başvuru durumu')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başvuru zamanı')),
                ('screening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ön değerlendirme puanı')),
                ('source_note', models.CharField(blank=True, max_length=250, verbose_name='Kaynak açıklaması')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red gerekçesi')),
                ('withdrawn_reason', models.TextField(blank=True, verbose_name='Geri çekilme gerekçesi')),
                ('assigned_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_job_applications', to='hr.employee', verbose_name='Atanan İK sorumlusu')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.candidate', verbose_name='Aday')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_applications', to='organizations.company', verbose_name='Şirket')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.jobrequisition', verbose_name='İşe alım talebi')),
            ],
            options={
                'verbose_name': 'İş başvurusu',
                'verbose_name_plural': 'İş başvuruları',
                'ordering': ['-applied_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['company', 'last_name', 'first_name'], name='hr_candidat_company_1463ee_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['company', 'source'], name='hr_candidat_company_749fb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='unique_candidate_email_per_company'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(condition=models.Q(('years_of_experience__isnull', True), ('years_of_experience__gte', 0), _connector='OR'), name='candidate_experience_non_negative'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['company', 'status', 'created_at'], name='hr_jobrequi_company_6875e0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['department', 'status'], name='hr_jobrequi_departm_4d50d6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['recruiter', 'status'], name='hr_jobrequi_recruit_4151f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobrequisition',
            constraint=models.UniqueConstraint(fields=('company', 'requisition_number'), name='unique_requisition_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='jobrequisition',
            constraint=models.CheckConstraint(condition=models.Q(('headcount__gte', 1)), name='job_requisition_headcount_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='jobrequisition',
            constraint=models.CheckConstraint(condition=models.Q(('filled_headcount__gte', 0)), name='job_requisition_filled_headcount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobrequisition',
            constraint=models.CheckConstraint(condition=models.Q(('filled_headcount__lte', models.F('headcount'))), name='job_requisition_filled_not_above_headcount'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['company', 'stage', 'status'], name='hr_jobappli_company_a09607_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['requisition', 'stage'], name='hr_jobappli_requisi_7f69d6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['candidate', 'status'], name='hr_jobappli_candida_5ce778_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['assigned_recruiter', 'status'], name='hr_jobappli_assigne_5ad5e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('requisition', 'candidate'), name='unique_candidate_application_per_requisition'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.CheckConstraint(condition=models.Q(('screening_score__isnull', True), models.Q(('screening_score__gte', 0), ('screening_score__lte', 100)), _connector='OR'), name='application_screening_score_between_0_and_100'),
        ),
    ]
