# Generated by Django 6.0.7 on 2026-08-04 19:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_candidate_jobrequisition_jobapplication_and_more'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('application_created', 'Başvuru oluşturuldu'), ('moved_to_screening', 'Ön elemeye taşındı'), ('moved_to_phone_screen', 'Telefon görüşmesine taşındı'), ('moved_to_interview', 'Mülakata taşındı'), ('moved_to_assessment', 'Değerlendirmeye taşındı'), ('moved_to_offer', 'Teklif aşamasına taşındı'), ('rejected', 'Reddedildi'), ('withdrawn', 'Aday geri çekildi'), ('hired', 'İşe alındı'), ('updated', 'Güncellendi')], max_length=40, verbose_name='İşlem türü')),
                ('previous_stage', models.CharField(blank=True, choices=[('applied', 'Başvurdu'), ('screening', 'Ön eleme'), ('phone_screen', 'Telefon görüşmesi'), ('interview', 'Mülakat'), ('assessment', 'Değerlendirme'), ('offer', 'Teklif'), ('hired', 'İşe alındı'), ('rejected', 'Reddedildi'), ('withdrawn', 'Aday geri çekildi')], max_length=30, verbose_name='Önceki aşama')),
                ('new_stage', models.CharField(choices=[('applied', 'Başvurdu'), ('screening', 'Ön eleme'), ('phone_screen', 'Telefon görüşmesi'), ('interview', 'Mülakat'), ('assessment', 'Değerlendirme'), ('offer', 'Teklif'), ('hired', 'İşe alındı'), ('rejected', 'Reddedildi'), ('withdrawn', 'Aday geri çekildi')], max_length=30, verbose_name='Yeni aşama')),
                ('previous_status', models.CharField(blank=True, choices=[('active', 'Aktif'), ('hired', 'İşe alındı'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri çekildi'), ('archived', 'Arşivlendi')], max_length=20, verbose_name='Önceki durum')),
                ('new_status', models.CharField(choices=[('active', 'Aktif'), ('hired', 'İşe alındı'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri çekildi'), ('archived', 'Arşivlendi')], max_length=20, verbose_name='Yeni durum')),
                ('note', models.TextField(blank=True, verbose_name='İşlem notu')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem zamanı')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.jobapplication', verbose_name='İş başvurusu')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_events', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi yapan kullanıcı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_events', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'İşe alım işlem kaydı',
                'verbose_name_plural': 'İşe alım işlem kayıtları',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['company', 'occurred_at'], name='hr_recruitm_company_5f5cc9_idx'), models.Index(fields=['application', 'occurred_at'], name='hr_recruitm_applica_e35e8e_idx'), models.Index(fields=['event_type', 'occurred_at'], name='hr_recruitm_event_t_c357f1_idx')],
            },
        ),
    ]
