# Generated by Django 6.0.7 on 2026-08-05 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_recruitmentevent'),
        ('organizations', '0003_company_tax_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentAIAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'Analiz ediliyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Analiz durumu')),
                ('overall_score', models.PositiveSmallIntegerField(default=0, verbose_name='Genel uyum puanı')),
                ('skill_score', models.PositiveSmallIntegerField(default=0, verbose_name='Beceri uyum puanı')),
                ('title_score', models.PositiveSmallIntegerField(default=0, verbose_name='Unvan uyum puanı')),
                ('experience_score', models.PositiveSmallIntegerField(default=0, verbose_name='Deneyim uyum puanı')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='Güçlü yönler')),
                ('risks', models.JSONField(blank=True, default=list, verbose_name='Riskler')),
                ('matched_skills', models.JSONField(blank=True, default=list, verbose_name='Eşleşen beceriler')),
                ('missing_skills', models.JSONField(blank=True, default=list, verbose_name='Eksik beceriler')),
                ('recommendation', models.CharField(blank=True, max_length=40, verbose_name='Öneri')),
                ('summary', models.TextField(blank=True, verbose_name='AI değerlendirme özeti')),
                ('ai_used', models.BooleanField(default=False, verbose_name='AI sağlayıcısı kullanıldı mı?')),
                ('ai_error', models.TextField(blank=True, verbose_name='AI hata özeti')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma zamanı')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='hr.jobapplication', verbose_name='İş başvurusu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_ai_assessments', to='organizations.company', verbose_name='Şirket')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_recruitment_ai_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Analizi isteyen kullanıcı')),
            ],
            options={
                'verbose_name': 'Recruitment AI değerlendirmesi',
                'verbose_name_plural': 'Recruitment AI değerlendirmeleri',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company', 'status', 'updated_at'], name='hr_recruitm_company_765bfe_idx')],
            },
        ),
    ]
