upstream glauria_web {
    server web:8001;
}

server {
    listen 80;
    server_name localhost glauria.dev www.glauria.dev 2.28.4.211;

    client_max_body_size 20M;

    location /static/ {
        alias /app/staticfiles/;
        access_log off;
        expires 30d;
    }

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_pass http://glauria_web;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
}
