# Generated by Django 6.0.7 on 2026-07-27 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20, verbose_name='Plan')),
                ('status', models.CharField(choices=[('trial', 'Deneme'), ('active', 'Aktif'), ('past_due', 'Ödeme bekliyor'), ('canceled', 'İptal edildi'), ('suspended', 'Askıya alındı')], default='trial', max_length=20, verbose_name='Abonelik durumu')),
                ('member_limit', models.PositiveIntegerField(default=5, verbose_name='Üye limiti')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Başlangıç tarihi')),
                ('current_period_ends_at', models.DateField(blank=True, null=True, verbose_name='Dönem bitiş tarihi')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Dönem sonunda iptal et')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Şirket aboneliği',
                'verbose_name_plural': 'Şirket abonelikleri',
            },
        ),
    ]
