# Generated by Django 6.0.7 on 2026-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_companysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_office',
            field=models.CharField(blank=True, max_length=120, verbose_name='Vergi dairesi'),
        ),
    ]
